language: node_js
node_js:
  - '12.14'
before_install:
  - openssl aes-256-cbc -K $encrypted_a7974dd46f9e_key -iv $encrypted_a7974dd46f9e_iv -in default.json.enc -out config/default.json -d
  - npm i -g npm@6.13.4
script:
  - echo "skipping tests"
services:
  - mongodb
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
before_deploy:
  - rm -rf node_modules
  - zip -r historyjam ./*
  - mkdir -p deploy
  - mv historyjam.zip deploy/historyjam.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: koreanhistoryjam-ci
    region: ap-northeast-2
    cleanup: true
    local_dir: deploy
    wait-until-deployed: true
    on:
      all_branches: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: koreanhistoryjam-ci
    key: historyjam.zip
    bundle_type: zip
    application: koreanhistoryjam
    deployment_group: koreanhistoryjam-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      all_branches: true
notifications:
  email:
    recipients:
      - jonghui.js@gmail.com
