language: node_js
node_js:
  - '12.14'
dist: trusty
before_install:
  - npm i -g npm@6.13.4
  - openssl aes-256-cbc -K $encrypted_a7974dd46f9e_key -iv $encrypted_a7974dd46f9e_iv
    -in default.json.enc -out config/default.json -d
services:
  - mongodb
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
before_deploy:
  - rm -rf node_modules
  - zip -r historyjam *
  - mkdir -p deploy
  - mv historyjam.zip deploy/historyjam.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: koreanhistoryjam-ci
    region: ap-northeast-2
    skip_cleanup: true
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: jonghui-js/historyjam
      branch: master
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: koreanhistoryjam-ci
    key: historyjam.zip
    bundle_type: zip
    application: koreanhistoryjam
    deployment_group: koreanhistoryjam-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: jonghui-js/historyjam
      branch: master
notifications:
  email:
    recipients:
      - jonghui.js@gmail.com
