version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/deploy/koreanhistoryjam/
    overwrite: yes

permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 1000
      runas: ec2-user
